name: Lint, Build, & Test
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'v4-client-js/**'
  push:
    branches:
      - main
      - master
      - "release/*"

defaults:
  run:
    working-directory: ./v4-client-js

jobs:
  js-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: "npm"

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_READ }}

      - name: Run eslint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
